from strategies.strategy import Strategy
from strategies.trend_momentum_strategy import TrendMomentumStrategy
from strategies.multi_moving_average_strategy import MultiMovingAverageStrategy, TradingPhase
from strategies.multi_moving_average_strategy_trend import MultiMovingAverageStrategyTrend
from strategies.volume_trend_momentum_strategy import VolumeTrendMomentumStrategy